### GET all games
GET http://localhost:5000/api/jeux

### GET games : short
GET http://localhost:5000/api/jeux/rapides

### GET games : long
GET http://localhost:5000/api/jeux/longs

### GET games : collaborative
GET http://localhost:5000/api/jeux/collaboratifs

### GET games : asymetric
GET http://localhost:5000/api/jeux/asymetriques

### GET games that necessites generalknowledge
GET http://localhost:5000/api/jeux/culture-generale

### GET games that necessites chance
GET http://localhost:5000/api/jeux/chance

### GET games that necessites reflexion
GET http://localhost:5000/api/jeux/reflexion

### GET games that necessites skill
GET http://localhost:5000/api/jeux/adresse

### GET 1 game
GET http://localhost:5000/api/jeux/1

### PUT  modify 1 game from its id
PUT http://localhost:5000/api/jeux/1

### GET all themes
GET http://localhost:5000/api/themes