INSERT INTO game (
`name`,
`summary`,
`duration_min_in_minuts`,
`player_nbmin`,
`player_nbmax`,
`player_agemin`,
`player_agemax`,
`collaborative`,
`asymetric`,
`gamerule_difficulty`,
`generalknowledge`,
`chance`,
`reflexion`,
`skill`
) VALUES 
("18 soldats du feu","Plongez au coeur d’un bâtiment en feu pour en sauver les victimes… mais attention aux explosions surprises !",45,2,6,NULL,NULL,1,0,2,NULL,2,2,NULL),
("51ème Etat","Après la crise, fondez votre propre état... un peu déjanté !",60,2,4,NULL,NULL,0,0,3,NULL,1,3,NULL),
("6 qui prend","Jeu de cartes, il faut défausser toutes ses cartes.",45,2,10,NULL,NULL,0,0,1,NULL,2,2,NULL),
("Agricola","La vie d'une famille de paysans : culture de champs, animaux de ferme... beau matériel.",120,1,5,NULL,NULL,0,0,3,NULL,1,3,NULL),
("Bamboleo","Il faut ôter des pièces sans faire tomber le plateau.",15,2,7,NULL,NULL,0,0,1,NULL,1,1,3),
("Bandido","Un jeu labyrinthique ! Aidez un bandit qui tente de s'échapper en creusant des tunnels.",5,1,4,NULL,NULL,1,0,1,NULL,1,1,NULL),
("BIG Idea","Jeu de parlotte : vous devez vendre votre super invention !",25,3,6,NULL,NULL,0,0,1,NULL,NULL,1,NULL),
("Brin de jasette","Parlons d'insolite...",30,3,8,NULL,NULL,0,0,1,NULL,2,1,NULL),
("Bugs","Découvrez les bases de la programmation informatique tout en coopérant.",25,1,4,NULL,NULL,1,0,1,NULL,2,2,NULL),
("Camelot","Combat de chevaliers... avec des cartes.",30,2,5,NULL,NULL,0,0,2,NULL,3,2,NULL),
("Carcassone La Cité","Construisons la cité de Carcassonne, avec ses murailles et ses ruelles.",30,2,4,NULL,NULL,0,0,2,NULL,1,3,NULL),
("Carcassone Préhistoire","La vie à la préhistoire : se faire des territoires de chasse, trouver des coins de pêche...",45,2,5,NULL,NULL,0,0,1,NULL,2,2,NULL),
("Chasse gardée","Chasseur et bûcheron contre animaux de la forêt.",40,2,2,NULL,NULL,0,0,2,NULL,2,2,NULL),
("Colons de Cathane","La construction d'un village et son développement... avec des cartes.",75,2,2,NULL,NULL,0,0,3,NULL,1,3,NULL),
("Convoi","Une histoire de train.",30,2,2,NULL,NULL,0,0,2,NULL,NULL,NULL,NULL),
("Dead of winter","Coopératif / semi-coopératif",60,2,5,NULL,NULL,1,0,3,NULL,NULL,NULL,NULL),
("Death Angel","Les marines débarquent dans un vaisseau d'aliens... et c'est le combat de cartes.",30,1,6,NULL,NULL,0,0,2,NULL,3,1,NULL),
("Deep sea Adventure","Jeu de scaphandrier, l'air se raréfie...",30,2,6,NULL,NULL,0,0,1,NULL,NULL,2,NULL),
("Diaballik","Jeu d'échecs avec des boules et des assiettes.",20,2,2,NULL,NULL,0,0,1,NULL,NULL,3,NULL),
("Dixit","Faire deviner la carte à laquelle on pense avec une simple expression. Attention, si tout le monde trouve, c’est perdu !",30,3,12,NULL,NULL,0,0,1,3,NULL,1,NULL),
("Dongeon twister","Duel dans un donjon + extensions",45,2,2,NULL,NULL,0,0,3,NULL,NULL,3,NULL),
("Dungeon lords","Le même principe que Dungeon Keeper Gold… Tu vois, petit, les méchants aussi peuvent gagner !",90,2,4,NULL,NULL,0,0,3,NULL,2,3,NULL),
("Eminent Domain","Coloniser la galaxie avec des cartes.",45,2,4,NULL,NULL,0,0,1,NULL,NULL,3,NULL),
("Forêt","Construire sa forêt et gérer les animaux qui y vivent (pas trop, juste assez)",15,2,4,NULL,NULL,0,0,2,NULL,NULL,3,NULL),
("Fresco","Accomplissez les tâches d'un peintre artistique... jeu de stratégie.",60,2,4,NULL,NULL,0,0,3,NULL,NULL,3,NULL),
("Guerre et Bêêêh","Trouvez la plus belle herbe pour votre troupeau... mais attention au loup !",15,2,2,NULL,NULL,0,0,2,NULL,1,3,NULL),
("Hanabi","Feux d'artifice avec des cartes.",30,2,5,NULL,NULL,0,0,1,NULL,2,2,NULL),
("Il était une fois","Raconter des histoires !",30,2,6,NULL,NULL,0,0,1,NULL,1,3,NULL),
("Imagine","Faire deviner un mot avec des cartes symboles",30,3,8,NULL,NULL,0,0,1,3,NULL,3,NULL),
("Kharnage","Essayer d'être le premier à la table de pique-nique (jeu de guerre par cartes)",15,2,4,NULL,NULL,0,0,1,NULL,NULL,1,NULL),
("King assassins","Roi contre assassins (jeu asymétrique).",20,2,2,NULL,NULL,0,0,1,NULL,NULL,3,NULL),
("L'Empereur","On joue des manchots",15,2,4,NULL,NULL,0,0,2,NULL,NULL,2,NULL),
("La glace et le ciel","Coopératif",15,2,4,NULL,NULL,1,0,2,NULL,NULL,3,NULL),
("Le désert interdit","Jeu coopératif contre la soif et la tempête de sable...",45,2,5,NULL,NULL,1,0,2,NULL,1,2,NULL),
("Les aventuriers du rail","Jeu de mémoire.",30,2,4,NULL,NULL,0,0,2,NULL,NULL,3,NULL),
("Les loups-garous de Thiercelieux","Loups-garous contre villageois... mais qui est qui ?",30,8,18,NULL,NULL,0,0,1,NULL,NULL,3,NULL),
("Louny Quest","Saurez-vous faire courir votre feutre entre les obstacles invisibles ?",20,2,5,NULL,NULL,0,0,1,NULL,NULL,1,3),
("Mainframe","Exécutez des Programmes, placez des Points d’accès et des Barrières, et prenez le contrôle du Serveur Central !",30,2,4,NULL,NULL,0,0,1,NULL,NULL,3,NULL),
("mars","Construisons des colonies sur Mars.",90,2,4,NULL,NULL,0,0,2,NULL,1,3,NULL),
("Mémoire 44","Reconstitution de batailles réelles... mais qui aura le dessus ?",60,1,9,NULL,NULL,0,0,2,NULL,NULL,3,NULL),
("Micro-mutants","Jeu de puces avec des insectes extra-terrestres qui ont des pouvoirs.",30,2,2,NULL,NULL,0,0,1,NULL,NULL,1,3),
("Migrato","Faites migrer plus d'oiseaux que votre adversaire.",15,2,2,NULL,NULL,0,0,1,NULL,1,2,NULL),
("Ninja","D'un côté le terroriste, de l'autre les gardiens d'une maison bourgeoise.",45,2,4,NULL,NULL,0,0,2,NULL,1,3,NULL),
("Not alone","S'évader de la planète avant que celle-ci ne nous absorbe...",30,2,7,NULL,NULL,0,0,2,NULL,3,3,NULL),
("Off the dead","Jeu coopératif : combat de zombies",60,1,4,NULL,NULL,1,0,2,NULL,3,3,NULL),
("Paf le singe","Un singe s'est réfugié sur les hauteurs d'une décharge. Il faut être le 1er à l'atteindre.",30,2,6,NULL,NULL,0,0,1,NULL,3,1,NULL),
("Pandémie","Jeu coopératif : enrayer 4 épidémies de la planète.",45,2,4,NULL,NULL,1,0,2,NULL,2,3,NULL),
("Pitch car","Jeu de pichenettes.",30,2,8,NULL,NULL,0,0,1,NULL,1,NULL,3),
("Polarity","Un jeu d'aimants.",15,2,4,NULL,NULL,0,0,1,NULL,NULL,NULL,3),
("Pollen","Un champ de fleurs. 2 ruches. Elaborez la meilleure stratégie !",15,2,2,NULL,NULL,0,0,2,NULL,NULL,3,NULL),
("Quirkle","Jeu de logique avec des symboles et des couleurs.",30,2,4,NULL,NULL,0,0,1,NULL,1,3,NULL),
("Race for the Galaxy","Coloniser la galaxie avec des cartes.",40,2,4,NULL,NULL,0,0,3,NULL,NULL,3,NULL),
("Rattus","La peste envahit l'Europe !",45,2,4,NULL,NULL,0,0,1,NULL,2,3,NULL),
("Richesses de France","Parcourir les régions de France en validant des étapes (plusieurs circuits)",60,2,4,NULL,NULL,0,0,1,NULL,3,1,NULL),
("Roll through the ages","Jeu compact où il faut développer la meilleure cité.",45,1,4,NULL,NULL,0,0,1,NULL,2,3,NULL),
("Sans foi ni loi","Serez-vous le plus prospère des cow-boys ?",60,2,6,NULL,NULL,0,0,2,NULL,3,2,NULL),
("Scrabble","Trouver les mots qui rapportent le plus de points.",60,2,6,NULL,NULL,0,0,1,NULL,1,3,NULL),
("Sherlock Holmes détective conseil","Coopératif",60,1,8,NULL,NULL,1,0,3,NULL,NULL,3,NULL),
("SIAM","Un genre d'échecs plus facile",15,2,2,NULL,NULL,0,0,1,NULL,NULL,3,NULL),
("Siggil","Coopératif – récupérer toutes ses cartes sur le plateau",20,1,4,NULL,NULL,1,0,1,NULL,NULL,3,NULL),
("Snow tails","Course de traîneaux.",45,2,5,NULL,NULL,0,0,2,NULL,3,2,NULL),
("Stronghold","D'un côté l'assaillant, de l'autre le défenseur du château.",120,2,4,NULL,NULL,0,0,3,NULL,NULL,3,NULL),
("Sutakku","Jeu de dé « stop ou encore ».",15,1,99,NULL,NULL,0,0,1,NULL,3,NULL,NULL),
("The game","Coopératif – se débarrasser de toutes ses cartes",20,1,5,NULL,NULL,1,0,1,NULL,NULL,3,NULL),
("The pyramid's deazdline","Construire une pyramide",20,2,6,NULL,NULL,0,0,1,NULL,1,1,NULL),
("Time stories","Voyagez à travers le temps et les réalités multiples.",90,2,4,NULL,NULL,0,0,3,NULL,NULL,3,NULL),
("Tsuro","Le principe : construire un chemin qui nous évite de sortir du plateau.",10,2,8,NULL,NULL,0,0,1,NULL,1,3,NULL),
("Tumbling dice","La pétanque... avec des dés et des pichenettes !!!",15,2,6,NULL,NULL,0,0,1,NULL,NULL,NULL,3),
("Une vie de chien","On est des chiens : marquer des pipis, trouver des nonos... se faire choper par la fourrière.",90,2,6,NULL,NULL,0,0,2,NULL,3,2,NULL),
("vendredi","Survivre sur son île déserte... avec des cartes.",25,1,1,NULL,NULL,0,0,2,NULL,2,3,NULL),
("Wasabi","Jeu de dés (?)",20,2,6,NULL,NULL,0,0,1,NULL,NULL,NULL,NULL),
("Zombies!!!","Inspiré du film : attaquer les zombies dans la ville et atteindre l'hélicoptère.",60,2,6,NULL,NULL,0,0,2,NULL,3,2,NULL),
("Couadsous","Un jeu à s’en retourner le cerveau ! Les meilleurs mémoires gagneront.",10,2,4,NULL,NULL,0,0,1,NULL,1,3,NULL)
;
INSERT INTO theme (`name`) VALUES ("espace"), ("nature"), ("animaux"), ("Halloween"), ("Asie"), ("histoire"), ("Moyen-âge");
